#!/bin/bash
#
# Launch an EPS job. Period.
#
#
# Authors: pirkka.ollinaho@fmi.fi
#          juha.lento@csc.fi

# Run options
#
export NAME=name
export MODEL=oifs
export HOST=$(hostname | cut -c 1-5)

# Import correct settings
#
source sources/${MODEL}_exp.$NAME # Experiment specific settings
source sources/${MODEL}_env.$HOST # Environment specific settings

# Broadcast general
#
printf '\n%s\n'   "OpenEPS `git tag`"
printf '\n%s'     "Running an ensemble of $ENS-members for ${MODEL^^}."
printf '\n%s\n\n' "Start date for ensemble is $SDATE and end date $EDATE"

# Check that all vital paths/executables exist
#
source scripts/general_test.bash

# Initialize
#
source scripts/general_init.bash

exit
# Launch bash/batch job
#
cd $WORK
printf "\n3) Submitting job...\n"
#sbatch scripts/job.bash 
bash scripts/main.bash &
printf "   ...done! Launcher exiting...\n\n"

exit 1
