#!/bin/bash

source $WORK/util_tools.bash

#cp ${DEFDIR}/eppes_init/*.dat eppes/day0
eppes_init_makefile 


# Each Day > 0: Run ensemble members, calculate scores, run Eppes

for j in $(seq 1 $EDATE) ; do
    for i in $(seq 0 $ENS) ; do
	i=$(printf "%03d" $i)
        emember_makefile $j $i
    done
    #mkdir -p day${j}/{eppes,ctrl}
    eppes_makefile $j
done

submakefiles=$(find day* -name Makefile -printf ' \\\n  %p')

cat > Makefile <<EOF
.PHONY: all
all: day${DAY}/eppes/oldsample.dat
include ${submakefiles}
EOF

