#!/bin/bash

# Get process id
nid=$(echo $@ | sed -e "s/\/job/ /g" -e 's/\/output/ /g' | cut -d " " -f 2 | tr -d ' ')
sleep 1

#date | echo `exec cut -b12-20` funceval ${nid} >> $runs/../master.log

#cd $cdate/job$nid

# Name nid=1 control run and other jobs pert$nid-1 
# Also, give nid three digits (clearer for job organization) 
#
nid=$(echo "$nid - 1" | bc)
if [ $nid -eq 0 ]; then
 name=ctrl
elif [ $nid -lt 10 ]; then
 name=pert00$nid
elif [ $nid -lt 100 ]; then
 name=pert0$nid
fi

# Change output to GRIB1
#
# sed these from initjob
grib_set=/appl/climate/bin/grib_set
exps=teps
runlen=48
outp=24
lista=""
listb=""

rm -f tempGG*
rm -f tempSH*

#set -ex
if [ 1 -eq 0 ]; then
for step in $(seq 24 $outp $runlen); do
 if [ $step -lt 100 ]; then
  step=0000$step
 else
  step=000$step
 fi
 for item in GG SH; do
  $grib_set -s editionNumber=1 ICM${item}${exps}+$step temp${item}+$step
 done
 lista="$lista tempGG+$step"
 listb="$listb tempSH+$step"
done

# Concatenate the output
#
# sed cdo from initjob, also add OMP threads with cdo="/appl/climate/bin/cdo -P nthreads"
cdo=/appl/climate/bin/cdo 
$cdo -cat $lista tempGG
$cdo -cat $listb tempSH
rm -f temp*+*

# Change GG into regular gaussian, and spectral into regular gaussian after changing
# divergence and vorticity into u- and v-winds.
# NOTE! the GG seems to result in too low res output, tried to change this in fort.4
# but didn't work...So extrapolate them into T255 grid for now.
$cdo -R copy tempGG tempGGrtemp
$cdo -remapcon2,t255grid tempGGrtemp tempGGr
$cdo -dv2uv tempSH tempSHrtemp
$cdo -R sp2gp tempSHrtemp tempSHr
rm -f temp*rtemp tempGG tempSH

# Divide output to individual files (don't know if this is worth it, but this 
# might make the file reading faster)
# sed the parameters from initjob

#ggpars=133
#shpars=
for item in var133; do
 $cdo -selvar,$item tempGGr temp_$item.grb
done
for item in var130 var131 var132 var152; do
 $cdo -selvar,$item tempSHr temp_$item.grb
done
$cdo -selzaxis,hybrid temp_var152.grb temp152
mv temp152 temp_var152.grb
fi
rm -f temp??r
# TEMP
# Do the same for analysis fields, take these from initial states
#
if [ 1 -eq 0 ]; then
rm -f temp_an_var*.grb*
cdo=/appl/climate/bin/cdo 
based=/wrk/ollinaho/t255_hayian
for date in 2013110312 2013110412; do
 $grib_set -s editionNumber=1 $based/$date/ICMGGg135INIUA temp_an_gg
 $cdo -R -selvar,var133   temp_an_gg         temp_an_qq
 $cdo -remapcon2,t255grid temp_an_qq         temp_an${date}_q
 rm -f temp_an_qq temp_an_gg
 $grib_set -s editionNumber=1 $based/$date/ICMSHg135INIT temp_an_sh
 $cdo -selvar,var130 temp_an_sh              temp_an${date}_t
 $cdo -dv2uv         temp_an_sh              temp_uv
 $cdo -selvar,var131 temp_uv                 temp_an${date}_u
 $cdo -selvar,var132 temp_uv                 temp_an${date}_v
 $cdo -selvar,var152 temp_an_sh              temp_an${date}_lnsp
 rm -f temp_an_sh temp_uv
done
for item in q t u v lnsp; do
 $cdo -cat temp_an2013110312_$item temp_an2013110412_$item temp_an_$item
done
rm -f temp_an2013*

$cdo -R -sp2gp temp_an_t    temp_an_var130.grb
$cdo -R -sp2gp temp_an_lnsp temp_an_var152.grb
rm -f temp_an_t temp_an_lnsp
mv temp_an_u temp_an_var131.grb
mv temp_an_v temp_an_var132.grb
mv temp_an_q temp_an_var133.grb
# Change to GRIB1
#for item in 130 152; do
# $grib_set -s editionNumber=1 temp_an_var${item}.grb2 temp_an_var${item}.grb
# rm -f temp_an_var${item}.grb2
#done
fi

# TEMP
# DO THIS IN initjob
# sed some stuff in cost function calculation and compile it
# Determine lat/lon/lev, length of time step and output interval
#
lon=768
lat=384
lev=91
tim=2700.0
OUTP=24
cp -f /homeappl/home/ollinaho/appl_sisu/oifs/EPSdev/scripts/postpro/calculate_cost_function_template_en.f90 calc_cost_en.f90
cp -f /homeappl/home/ollinaho/appl_sisu/oifs/EPSdev/scripts/postpro/wgrib .
# Modify and compile fortran files
#
sed -i -e "s/\:\:lon=320/\:\:lon=$lon/g"      calc_cost_en.f90
sed -i -e "s/\:\:lat=160/\:\:lat=$lat/g"      calc_cost_en.f90
sed -i -e "s/\:\:levmax=31/\:\:levmax=$lev/g" calc_cost_en.f90
sed -i -e "s/ntime=40/ntime=2/g"              calc_cost_en.f90 # dates in forecast file
sed -i -e "s/ntime2=20/ntime2=2/g"            calc_cost_en.f90 # dates in analysis file
sed -i -e "s/nvar=8/nvar=8/g"                 calc_cost_en.f90
ftn calc_cost_en.f90

mkdir -p pp
cp -f temp_an_var*.grb pp/.
cp -f temp_var*.grb pp/.
mkdir -p wgrib1

cat > infile.txt <<EOF
ctrl
/wrk/ollinaho/testiEPS/data/2013110212/job1
/wrk/ollinaho/testiEPS/data/2013110212/job1
/wrk/ollinaho/testiEPS/data/2013110212/job1
2013110212
EOF

./a.out
