# Requires:

.SECONDARY: $(cdate)/%/outfile 

.PHONY : all

all : $(TARGET_A0)

$(TARGET_A0) : $(ALL_TARGETS_A)
	$(RULE_A)

$(TARGET_B0) : $(TARGET_B1)
	$(RULE_B)

$(TARGET_C0) : $(TARGET_C1)
	$(RULE_C)

$(TARGET_D0) : $(TARGET_D1)
	$(RULE_D)

$(TARGET_E0) : $(TARGET_E1)
	$(RULE_E)



