#!/bin/bash

# Get process id
nid=$(pwd | grep -o 'job[0-1000]' | grep -o [0-1000])
pwd

date | echo `exec cut -b12-20` runmodel ${nid} >> $runs/../master.log

oifs_exe=
ifsdata=
ifsdata2=
grib_samples=
exp_data=
oifs_res=
exp_name=

#cd $runs/$cdate/job${nid}

# Name nid=1 control run and other jobs pert$nid-1 
# Also, give nid three digits (clearer for job organization) 
#
echo $nid
if [ $nid -eq 0 ]; then
 name=ctrl
elif [ $nid -lt 10 ]; then
 name=pert00$nid
elif [ $nid -lt 100 ]; then
    name=pert0$nid
else
    name=pert$nid
fi
name=ctrl

rm -f ICM*+00*

#ln -sf ${exp_data}/${name}_ICMCL${exp_name}INIT  ICMCL${exp_name}INIT
#ln -sf ${exp_data}/${name}_ICMGG${exp_name}INIT  ICMGG${exp_name}INIT
#ln -sf ${exp_data}/${name}_ICMGG${exp_name}INIUA ICMGG${exp_name}INIUA
#ln -sf ${exp_data}/${name}_ICMSH${exp_name}INIT  ICMSH${exp_name}INIT
ln -sf /home/ollin/projects/OIFS/oifs38r1v04/t21test2/ICMGGepc8INIT  ICMGG${exp_name}INIT
ln -sf /home/ollin/projects/OIFS/oifs38r1v04/t21test2/ICMGGepc8INIUA ICMGG${exp_name}INIUA
ln -sf /home/ollin/projects/OIFS/oifs38r1v04/t21test2/ICMSHepc8INIT  ICMSH${exp_name}INIT
ln -sf /home/ollin/projects/OIFS/oifs38r1v04/t21test2/ifsdata/ .

ln -sf ${ifsdata}/climatology ./ifsdata
ln -sf ${ifsdata}/rtables
ln -sf ${ifsdata2}/38r1/climate/${oifs_res}l_2
# REMOVE THIS WHEN DONE IN pargen
#cp -f $runs/../scripts/${exp_name}.namelist fort.4
cp -f /home/ollin/projects/OIFS/oifs38r1v04/t21test2/fort.4 .


#  DR_HOOK controls the tracing facility in OpenIFS.
#  0 = off, 1 = on.
export DR_HOOK=1

#  Set number of OpenMP threads to use. Must be compiled
#  with openmp for this to have any effect.
export OMP_NUM_THREADS=2


#  Set defaults build type; either optimised (opt) or non-optimized (noopt)
OIFS_COMP=gnu
OIFS_BUILD=opt
OIFS_GRIB_API_DIR=/home/ollin/Install_software/grib-api

#  Set the GRIB_SAMPLES_PATH to your installation.
#  Assumes you have installed as describe in the OpenIFS documentation.
#  Make sure LD_LIBRARY_PATH contains the grib_api 'lib' directory.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OIFS_GRIB_API_DIR/lib
export GRIB_SAMPLES_PATH=$OIFS_GRIB_API_DIR/share/grib_api/ifs_samples/grib1_mlgrib2

#  Name of openifs executable in oifs/make/build/bin
MASTER=../make/$OIFS_COMP-$OIFS_BUILD/oifs/bin/master.exe

# Increase stack memory (model may crash with SEGV otherwise)
ulimit -s unlimited
