#!/bin/bash
#
# Targets and rules for makefile
#
# target_1   - the final target that make will try to reach
# prereq_1   - prerequirements of TARGET_1
# recipe_1     - commands to execute once NEEDED_1 are available
#
# target_2   - what TARGET_2 aims to provide
# prereq_2   - prerequirements of TARGET_2
# recipe_2     - commands to execute once NEEDED_2 are available
#
# target_3   - what TARGET_3 aims to provide
# prereq_3   - prerequirements of TARGET_3
# recipe_3     - commands to execute once NEEDED_3 are available
#
# etc.
#
# Keywords:
# MAIN - points to root of current date dir (e.g. MAIN/finished --> day1/finished)
# DIR  - indicates position of perturbation folder
#        (e.g. ../$ndate/DIR/infile --> ../day2/pert000/infile)

source $WORK/util_tools.bash

pert_struct=$SUBDIR_NAME


target_3=""

target_2="infile"
prereq_2=""
recipe_2=(
    "cd \$(dir \$@) ; \
     $serial ${SCRI}/link.bash ; \
     echo > infile "
)
applyto_2=individual


target_1="MAIN/date_finished"
prereq_1="infile"
recipe_1=(
    ""
)
applyto_1=main_all


# Loop through all targets
write_makefile

